### PR TITLE
Add way to run vader tests locally and in travis

### PR DESCRIPTION
**Pull request by mandos**

### CODE REVIEW

**Comment by rodjek** [comment]
Awesome, this is a nice start to a test suite! I've added a commit to get the tests running on neovim

**Comment by mandos** [comment]
I will setup travis for test both neovim and vim, and it would be end for this PR.

**Comment by mandos** [comment]
I think I finished for now, tests on travis will be run on vim 7.4 and on nighly build of neovim. In future we can setup travis to use also nightly builds of vim.

**Comment by mandos** [comment]
@rodjek Would you like to merge it and add this project to travis ci?

**Pull request merged**
