### PR TITLE
Merge multiple PR's

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by rlex** [comment]
Maybe you can fork it? Author does not seem to be interested in this addon anymore.

**Comment by roidelapluie** [comment]
You can find that there https://github.com/roidelapluie/vim-puppet

**Comment by evidex** [comment]
Also pulling this into my fork at https://github.com/evidex/vim-puppet

I'll happily take PR's and issues against that repo.

**Comment by roidelapluie** [comment]
Closing this PR, thanks @evidex

**Pull request closed without merging**
